#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN {
	IO::Socket::SSL::set_ctx_defaults(
		'SSL_verify_mode' => 0 #'SSL_VERIFY_NONE'
        );
	$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = '0';
	unshift @INC, "$FindBin::Bin/../lib";
}

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('EppClient');
